openapi: 3.0.0
info:
  title: Webropay Api
  description: Gerência contratos, sendo possível cadastrar um novo, editar o status
    e visualizar todos os contratos.
  termsOfService: http://localhost:8080/webropay-api/v1/termo-uso
  contact:
    name: Suporte
    url: http://localhost:8080/webropay-api/v1/suporte
    email: suporte@webropayapi.com
  version: 1.0.0
servers:
- url: http://localhost:8080/webropay-api/v1
tags:
- name: Contratos
paths:
  /contract:
    post:
      tags:
      - Contratos
      summary: Cadastra Contrato
      description: Possibilita cadastrar um novo contrato
      operationId: newContract
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new_contract'
        required: false
      responses:
        "201":
          description: Cadastro efetuado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/new_contract'
        "400":
          description: Requisição inválida
          content: {}
        "500":
          description: erro no servidor
          content: {}
      x-codegen-request-body-name: contract_
      x-swagger-router-controller: Contratos
  /contract/{id}:
    put:
      tags:
      - Contratos
      summary: Altera status
      description: Altera o status de um contrato
      operationId: editStatus
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/edit_status'
        required: false
      responses:
        "200":
          description: Alteração feita com sucesso
          content: {}
        "400":
          description: Requisição inválida
          content: {}
        "500":
          description: erro no servidor
          content: {}
      x-codegen-request-body-name: edit_contract
      x-swagger-router-controller: Contratos
  /contract/all:
    get:
      tags:
      - Contratos
      summary: Consulta contratos
      description: Lista todos os contratos cadastrados
      operationId: listContracts
      responses:
        "201":
          description: Consulta efetuada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/new_contract'
        "400":
          description: Requisição inválida
          content: {}
        "500":
          description: erro no servidor
          content: {}
      x-swagger-router-controller: Contratos
components:
  schemas:
    edit_status:
      type: object
      properties:
        newStatus:
          type: boolean
          example: true
    new_contract:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        description:
          type: string
          example: contrato de adesão do plano de pagamento
        status:
          type: boolean
          example: true
      example:
        description: contrato de adesão do plano de pagamento
        id: 1
        status: true
